import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fork, execFileSync } from 'node:child_process';
import { once } from 'node:events';
import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
const backend = new URL('../', import.meta.url);

test('API data, relationships and sessions survive restart; backups and migration are consistent', async t => {
 const directory = mkdtempSync(join(tmpdir(), 'ecowatch-db-test-'));
 const legacy = join(directory,'legacy'); mkdirSync(legacy);
 writeFileSync(join(legacy,'community-reports.json'), JSON.stringify([{id:'legacy-site',reports:[
  {id:'legacy-report',reporterId:'missing-user',latitude:1,longitude:1,reportedAt:'2024-01-01T00:00:00Z'}]}]));
 let modelCalls = 0;
 const model = http.createServer((req,res) => { modelCalls++; res.setHeader('Content-Type','application/json'); res.end(JSON.stringify({mining_detected:true,probability:0.8,model_version:'test-model',mask:[[1]]})); });
 model.listen(0,'127.0.0.1'); await once(model,'listening');
 t.after(() => model.close());
 const env = { ...process.env, DATABASE_PATH:join(directory,'test.sqlite'), LEGACY_DATA_DIR:legacy, SEED_DEMO_DATA:'true', MODEL_API_URL:`http://127.0.0.1:${model.address().port}` };
 let child, base;
 const start = async () => {
  child = fork(new URL('../fixtures/server.js', import.meta.url), [], { env, execArgv:['--experimental-sqlite'], stdio:['ignore','pipe','pipe','ipc'] });
  let errors=''; child.stderr.on('data', chunk => { errors += chunk; });
  const port = await Promise.race([once(child,'message').then(([port]) => port),once(child,'exit').then(() => { throw new Error(errors); })]);
  base=`http://127.0.0.1:${port}/api`;
 };
 const stop = async () => { child.kill(); await once(child,'exit'); };
 t.after(() => { if (child?.exitCode === null) child.kill(); });
 const request = async (path, method='GET', body, token) => {
  const response = await fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token ? {Authorization:`Bearer ${token}`} : {})},body:body ? JSON.stringify(body) : undefined});
  const text=await response.text(); return {status:response.status,body:text ? JSON.parse(text) : null};
 };
 await start();
 const admin = (await request('/auth/login','POST',{email:'ADMIN@ecowatch.local',password:'admin123'})).body;
 assert.ok(admin.token);
 const account = {name:'Test Reporter',email:'test@example.com',password:'password123'};
 const registered = await request('/auth/register','POST',account); assert.equal(registered.status,201);
 const token=registered.body.token;
 assert.equal((await request('/auth/register','POST',{...account,email:'TEST@example.com'})).status,400);
 assert.equal((await request('/auth/login','POST',{email:account.email,password:'wrong'})).status,401);
 assert.equal((await request('/incidents','POST',{type:'Mining',lat:5,lng:-1},token)).status,403);
 const created=await request('/incidents','POST',{type:'Mining',lat:5,lng:-1,authorities:['Police'],notes:'Persistent evidence'},admin.token);
 assert.equal(created.status,201); const id=created.body.id;
 assert.equal((await request(`/incidents/${id}/status`,'PATCH',{status:'Resolved'},admin.token)).status,200);
 assert.equal((await request('/incidents','POST',{type:'Mining',lat:5,lng:-1,authorities:['Not an authority']},admin.token)).status,400);
 assert.equal((await request('/incidents')).body.length,11);
 const submitted=await request('/community-reports','POST',{latitude:6,longitude:-1,notes:'Observation'},token);
 assert.equal(submitted.status,201); assert.equal(submitted.body.predictionError,null); const siteId=submitted.body.site.id;
 assert.equal((await request('/community-reports','POST',{latitude:6,longitude:-1},token)).status,409);
 assert.equal((await request('/community-reports','POST',{latitude:91,longitude:0},token)).status,400);
 const second=(await request('/auth/register','POST',{...account,email:'second@example.com'})).body;
 assert.equal((await request('/community-reports','POST',{latitude:6.0001,longitude:-1},second.token)).body.site.reportCount,2);
 const analysis = await request('/predictions/coordinate','POST',{latitude:7,longitude:-1,date_start:'2022-01-01',date_end:'2023-01-01'});
 assert.equal(analysis.status,200); assert.ok(analysis.body.analysisId);
 const callsBeforeReport = modelCalls;
 const reused = await request('/community-reports','POST',{latitude:7,longitude:-1,analysisId:analysis.body.analysisId},token);
 assert.equal(reused.status,201);
 assert.equal(modelCalls,callsBeforeReport, 'Map reports must not call the model again');
 assert.equal(reused.body.prediction.mining_detected,true);
 assert.equal(reused.body.site.latestPrediction.model_version,'test-model');
 const copiedRun = (await request('/predictions/history')).body.runs.find(run => run.source==='community-report' && run.latitude===7);
 assert.equal(copiedRun.dateStart,'2022-01-01'); assert.equal(copiedRun.dateEnd,'2023-01-01');
 assert.equal((await request('/community-reports','POST',{latitude:8,longitude:-1,analysisId:analysis.body.analysisId},token)).status,400);
 assert.equal((await request('/community-reports','POST',{latitude:8,longitude:-1,analysisId:'missing'},token)).status,400);
 assert.equal(modelCalls,callsBeforeReport);
 assert.ok(callsBeforeReport >= 3, 'Direct reports still run satellite checks');
 await stop(); await start();
 assert.equal((await request('/auth/me','GET',null,token)).status,200);
 assert.equal((await request('/auth/login','POST',account)).status,200);
 const incident=(await request(`/incidents/${id}`)).body; assert.equal(incident.status,'Resolved'); assert.deepEqual(incident.authorities,['Police']);
 assert.equal((await request(`/reports/${id}`)).body.description,'Persistent evidence');
 const pdf=await fetch(base+`/reports/${id}/pdf`); assert.equal(pdf.status,200); assert.match(await pdf.text(),/^%PDF/);
 assert.equal((await request('/stats')).body.total,11);
 const site=(await request('/community-reports')).body.sites.find(site => site.id===siteId); assert.equal(site.reportCount,2); assert.equal(site.latestPrediction.model_version,'test-model');
 assert.equal((await request('/predictions/history')).body.runs.length,4);
 assert.equal((await request('/auth/logout','POST',null,token)).status,204);
 assert.equal((await request('/auth/me','GET',null,token)).status,401);
 const backup=join(directory,'backup.sqlite');
 execFileSync(process.execPath,['--experimental-sqlite','src/database/manage.js','backup',backup],{cwd:backend,env});
 const db=new DatabaseSync(backup);
 assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');
 assert.deepEqual(db.prepare('PRAGMA foreign_key_check').all(),[]);
 assert.equal(db.prepare('SELECT count(*) AS n FROM community_reports').get().n,4);
 assert.equal(db.prepare("SELECT disabled FROM users WHERE id='missing-user'").get().disabled,1);
 assert.equal(db.prepare("SELECT count(*) AS n FROM schema_migrations WHERE version='legacy-import-v1'").get().n,1);
 assert.ok(db.prepare('SELECT password_hash FROM users WHERE email=?').get(account.email).password_hash !== account.password);
 assert.throws(() => db.prepare('INSERT INTO community_reports VALUES (?,?,?,?,?,?,?,?)').run('bad','no-site',null,1,1,null,null,'now'),/FOREIGN KEY/);
 db.close(); await stop();
});

test('production starts without demo credentials and empty reports return 404', async t => {
 const directory=mkdtempSync(join(tmpdir(),'ecowatch-production-test-'));
 const env={...process.env,NODE_ENV:'production',SEED_DEMO_DATA:'false',DATABASE_PATH:join(directory,'production.sqlite'),LEGACY_DATA_DIR:directory};
 execFileSync(process.execPath,['--experimental-sqlite','src/database/manage.js','init'],{cwd:backend,env});
 const db=new DatabaseSync(env.DATABASE_PATH);
 assert.equal(db.prepare('SELECT count(*) AS n FROM users').get().n,0);
 assert.equal(db.prepare('SELECT count(*) AS n FROM incidents').get().n,0);
 assert.equal(db.prepare('SELECT count(*) AS n FROM authorities').get().n,5);
 db.close();
 const child=fork(new URL('../fixtures/server.js',import.meta.url),[],{env,execArgv:['--experimental-sqlite'],stdio:['ignore','ignore','pipe','ipc']});
 t.after(() => child.kill());
 const [port]=await once(child,'message');
 assert.equal((await fetch(`http://127.0.0.1:${port}/api/reports/latest`)).status,404);
 child.kill(); await once(child,'exit');
});
