"use client"

import { apiUrl } from "@/lib/api"

export default function GeneratePdfButton() {
  // Download the PDF generated by the Express backend.
  const downloadGeneratedPDF = () => {
    window.location.href = apiUrl("/reports/latest/pdf")
  }

  return (
    <div className="flex justify-center mt-8 mb-8">
        <button onClick={downloadGeneratedPDF}
        className="inline-flex items-center px-4 py-2 rounded-lg bg-[#4a5e1a] text-white text-sm font-semibold hover:bg-[#3a4d12] transition">
         Generate PDF
        </button>
    </div>
  )
}
